//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrongEnergyCompany.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MadeniYağlar_DatabaseEntities : DbContext
    {
        public MadeniYağlar_DatabaseEntities()
            : base("name=MadeniYağlar_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fatura> Fatura { get; set; }
        public virtual DbSet<Il> Il { get; set; }
        public virtual DbSet<KargoFirma> KargoFirma { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<SatisElemani> SatisElemani { get; set; }
        public virtual DbSet<Sepet> Sepet { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<SirketYonetici> SirketYonetici { get; set; }
        public virtual DbSet<Ulke> Ulke { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
