//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrongEnergyCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SirketYonetici
    {
        public int YoneticiID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> TCKimlikNo { get; set; }
        public string Unvan { get; set; }
        public string Eposta { get; set; }
        public string Adres { get; set; }
        public string TelNo { get; set; }
        public string UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
